name: Build and Test with Bazel
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'
      - name: Download dependencies
        run: python3 utils/git-sync-deps
      - name: Mount Bazel cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.bazel/cache
          key: bazel-cache-${{ runner.os }}
      - name: Build All
        run: bazel --output_user_root=~/.bazel/cache build //...
      - name: Test All
        run: bazel --output_user_root=~/.bazel/cache test //...
